package std:io;

interface stdout {
  write: func(text: list<u8>);
  read: func() -> list<u8>;
}

interface files {
  exists: func(path: list<u8>) -> bool;
  write-access: func(path: list<u8>) -> bool;
  read-access: func(path: list<u8>) -> bool;

  write: func(path: list<u8>, text: list<u8>);
  read: func(path: list<u8>) -> list<u8>;
}
