(module
    (global $x (mut i32) (i32.const 0))
    (global $y (mut i32) (i32.const 0))
    (global $a (mut f32) (f32.const 0))
    (func (export "_start")
        (i32.const 0xff)
        (global.set $x)
        (global.get $x)
        (i32.const 1)
        (i32.add)
        (global.set $y)
        (global.get $y)
        (f32.reinterpret_i32)
        (global.set $a)
    )
)
