(module
    (func (export "_start")
        (local $x i32)
        (local $y i32)
        (local $a f32)
        (i32.const 0xff)
        (local.set $x)
        (local.get $x)
        (i32.const 1)
        (i32.add)
        (local.set $y)
        (local.get $y)
        (f32.reinterpret_i32)
        (local.set $a)
    )
)
