pub const Token = union(enum) {
    integer: []const u8,
    float: []const u8,
    string: []const u8,
    char: []const u8,
    left_parenthesis,
    right_parenthesis,
    left_bracket,
    right_bracket,
    left_brace,
    right_brace,
    comma,
    dot,
    plus,
    minus,
    slash,
    asterix,
    caret,
    percent,
    double_less,
    double_more,
    less,
    more,
    less_equal,
    more_equal,
    double_equal,
    bang_equal,
    newline,
    indentation,
    dedentation,
    end,
}
